POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "testuser4",
  "password": "testpassword"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "testuser4",
  "password": "testpassword"
}
###
GET http://localhost:5000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODMwZGE3NzQxZjIxMjQzY2Y4YzhiMGMiLCJpYXQiOjE3NDgwMzIxMjEsImV4cCI6MTc0ODAzNTcyMX0.PbaoV1e74SGC2FuGZ58ltplGV2kUdg-9KL7oFJewfyg
###
POST http://localhost:5000/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODMwZGE3NzQxZjIxMjQzY2Y4YzhiMGMiLCJpYXQiOjE3NDgwMzIxMjEsImV4cCI6MTc0ODAzNTcyMX0.PbaoV1e74SGC2FuGZ58ltplGV2kUdg-9KL7oFJewfyg

{
  "title": "Test Note 3 ",
  "content": "This is a test note 3."
}
###
DELETE http://localhost:5000/notes/6830db2d77b0c07f51d34d31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODMwZGE3NzQxZjIxMjQzY2Y4YzhiMGMiLCJpYXQiOjE3NDgwMzIxMjEsImV4cCI6MTc0ODAzNTcyMX0.PbaoV1e74SGC2FuGZ58ltplGV2kUdg-9KL7oFJewfyg